name: Markdown Lint
on:
    pull_request:
      branches:
        - main  # Or your default branch
jobs:
       lint:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v4
           - name: Install markdownlint-cli
             run: npm install -g markdownlint-cli
           - name: Lint Markdown files
             run: markdownlint '**/*.md'
